### ISSUE TITLE
Table rendering

### ISSUE THREAD

**Issue by taa1** [sunaku/md2man#21]
Hi,

Original markdown text file: http://pastebin.com/pb5pA4vD

Rendered output using `md2man-roff md2man-test.1.md`: http://pastebin.com/Tgd2cUav

1. How do I get an extra blank line *above* the text "Table 2" and "Table 3"? You can see I have two newlines but they seem to get stripped.

2. My ultimate goal is to have Table 2 and/or Table 3 rendered as the manually created Table 4. How do I get line wrapping within a cell?

**Comment by sunaku** [comment]
Sorry for the late response. :cold_sweat:

## Regarding item 1

Newlines are _not_ being stripped because "new paragraph" directives (`.PP`) are being emitted correctly just before each "Table _N_" line in the Roff output:

```sh

$ bundle exec md2man-roff test.md | grep -P -B1 'Table \d'
.PP
Table 1
--
.PP
Table 2
--
.PP
Table 3
--
.PP
Table 4
```

How `man -l` chooses to display those `.PP` directives is beyond my control. :sunrise_over_mountains:  I suppose we could modify md2man to emit multiple `.PP` directives to start every new paragraph but it doesn't feel like the right thing to do. :scream: 

## Regarding item 2

This is also beyond my control. :sunrise_over_mountains: You'll have to look at how the [Redcarpet markdown parser](https://github.com/vmg/redcarpet) deals with multi-line table cells. :dart:

Hope that helps! :sweat_smile:

**Comment by taa1** [comment]
I do not have the intelligence to patch Redcarpet so I guess md2man just isn't for me. Thanks for trying to help, though.
